name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ f0cd0549b0de74367629131ced46d5ba }}
          TIMEZONE: Asia/Seoul
